tap_install:
    sensitive_values:
        shared:
            ingress_domain: ENC[AES256_GCM,data:fXmo0Pn0ZI1Yy7hUA7Vuzo9D0/G77nnc3JpR0cTJDN5WYFi7lKuZnYgg3nQVTuktIg==,iv:73zGqe/XfhdksN4eT9vTY8M0lkvI7yg7g/nLNPXDkjk=,tag:ndJAVnCtP81WzpY3jW4vtA==,type:str]
            ingress_issuer: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140kfw9jqh7d63svrgf8rpjaf8mteg507va4s98pnjtl975qe6stqfpaxvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSUV2UnQzdktxVkZ0cVEv
            Z2owTmFXTW1pejdzMXRWTXFSbVRDWFNNamc0CllQMGlXbXd2NW54UHJ2TExtM1JK
            cDRBN25TdUFvSnVqTVJQbDVjalJ1a0kKLS0tIDJZd1ZRUXpKRTl4NzhpQVpNTzlj
            ZHpLVnM3Mk5ES1ljN1NFNTFFcy9FbWcKBP0KDJ6L/rdV2EsrscudU6uTWKag+5uu
            WfVZhM3N6z3pu5ERV4L4UDsz6SB0e6KBXwWMH2fYvfC9DI7GMKaswg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T13:16:54Z"
    mac: ENC[AES256_GCM,data:4leO8OveRPAaOj4Za7gFR1p+M03EY5NKs4vKKNNmjv3OFidlhZPqKisBIVDFIosO2JNWPolQ9gpb0iQ5YSGaNhvPHbvEmxUyDd9288gfovklph8Roq3oLwVgc9l7tU+UBtUIczUK7wQYMSuBusrn2/ON+rinEuwWAoISjLyuIjQ=,iv:vICI76dWCHxjbyndMvMekgAAWZCEiExzCr/dmjc5VIw=,tag:NELTZlbyEpI1d8RQDOwPEA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
